### ISSUE TITLE
server closed the connection unexpectedly - poll?

### ISSUE THREAD

**Issue by jgengo** [djrobstep/pgnotify#3]
Hello,

I'm giving a. try to pgnotify, and noticing that after few seconds/minutes I receive this error:

```
Traceback (most recent call last):
  File "main.py", line 33, in <module>
    handle_signals=SIGNALS_TO_HANDLE,
  File "/usr/local/lib/python3.7/site-packages/pgnotify/notify.py", line 138, in await_pg_notifications
    cc.poll()
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

It seems to be due somehow to the fact it can't stay connected to the database, is there a workaround or something to do to avoid that?

Thank you

**Comment by jgengo** [comment]
ok I think I got it, the timeout parameter is here to make a "fake" select to avoid being ejected, am I wrong?

Thank you for your time and sorry for bothering.

**Comment by djrobstep** [comment]
Not sure just from the message what exactly might be causing this disconnection. But unless I'm misremembering, a connection for `LISTEN`ing has the same behaviour as any other connection.

Connection pooling can sometimes cause trouble from the client side, so turning that off can sometimes be a good troubleshooting step.

**Comment by jgengo** [comment]
Hello,

I am really sorry for bothering you with this. I finally endup to find what was my issue. 

On OSX, VPNkit is looking for an idling TCP connection and was shutting down the connection. After trying without docker it was working well. So I updated the config properties of docker to avoid this problem!

Thanks for your time!

**Comment by djrobstep** [comment]
No worries, glad you solved it and doubly glad it wasn't a bug on my part!
